test: output parameters

diff --git a/.github/workflows/03_build.yml b/.github/workflows/03_build.yml
--- a/.github/workflows/03_build.yml
+++ b/.github/workflows/03_build.yml
@@ -8,6 +8,14 @@ jobs:
     steps:
       - uses: actions/checkout@v4.1.5
       - name: Run my own container action
+        id: my-action
         uses: ./
         with:
           who-to-greet: '@jdemaagd'
+      - name: Output the answer
+        run: echo "The answer is ${{ steps.my-action.outputs.answer }}"
+      - name: Test the container
+        if: ${{ steps.my-action.outputs.answer != 42 }}
+        run: |
+          echo "::error file=entrypoint.sh,line=4,title=Error in container::The answer was not expected"
+          exit 1
