Dev (#11)
* test: ci/cd pipeline workflows

* test: checkout actions

* test: tree

* test: environments

* fix: indentation

* test: environments n parallel jobs

* fix: accessing env secret/vars

* refactor: action env secrets/vars

* test: new workflow

* test: injection script

* test: only triggers on pr

* test: debugging/logging

* test: act via docker

* test: docker action

* test: output parameters

* test: incorrect parameter

* test: composite action

diff --git a/.github/workflows/03_build.yml b/.github/workflows/03_build.yml
--- a/.github/workflows/03_build.yml
+++ b/.github/workflows/03_build.yml
@@ -1,6 +1,12 @@
 name: Building GitHub Actions
 
+<<<<<<< HEAD
+#on: [push]
+on:
+  workflow_dispatch
+=======
 on: [push]
+>>>>>>> main
 
 jobs:
   ci:
@@ -8,6 +14,28 @@ jobs:
     steps:
       - uses: actions/checkout@v4.1.5
       - name: Run my own container action
+<<<<<<< HEAD
+        id: my-action
         uses: ./
         with:
           who-to-greet: '@jdemaagd'
+      - name: Output the answer
+        run: echo "The answer is ${{ steps.my-action.outputs.answer }}"
+      - name: Test the container
+        if: ${{ steps.my-action.outputs.answer != 42 }}
+        run: |
+          echo "::error file=entrypoint.sh,line=4,title=Error in container::The answer was not expected"
+          exit 1
+
+    # steps:
+    #   - name: Set the value
+    #     id: step_one
+    #     run: |
+    #       echo "action_state=yellow" >> "$GITHUB_ENV"
+    #   - run: |
+    #       echo "${{ env.action_state }}" # This will output 'yellow'
+=======
+        uses: ./
+        with:
+          who-to-greet: '@jdemaagd'
+>>>>>>> main
